development:
   adapter: sqlite3
   database: /Library/Application Support/REFx4/Database/refx4development.sqlite3
   pool: 5
   timeout: 5000

production:
   adapter: sqlite3
   database: /Library/Application Support/REFx4/Database/refx4production.sqlite3
   pool: 5
   timeout: 5000
